name: Package Artifacts

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.ref }}
  
jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test and Build Package
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - name: build
      run: |
        npm install
        npm run build
        npm test
        node ./scripts/signin.js run
        npm run integ
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          NPM_VERSION_TYPE: ${{ secrets.NPM_VERSION_TYPE }}
    - name: Release
      uses: JS-DevTools/npm-publish@v2
      with:
        token: ${{ secrets.NPM_TOKEN }}
