name: Package Artifacts

on:
  push:
    branches: [ "wiki" ]

concurrency:
  group: ${{ github.ref }}
  
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        npm install
        npm run docs
    - name: Update
      run: ./scripts/update-wiki.sh
      env:
        WIKI_DIR: 'wiki'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}